### ISSUE TITLE
Kibana Docker Fails to start after installing timelion-extras

### ISSUE THREAD

**Issue by Shifter2600** [rashidkpc/timelion-extras#1]
Adding the timelion-extras-4.x is definatly the cause becuase I can delete the folder and it starts fine after.
I am using Kibana 4.6.1 Docker 
Here is the Kibana Log.
FATAL { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js']
  { [Error: EACCES: permission denied, open '/opt/kibana/optimize/bundles/sense.entry.js']
     errno: -13,
     code: 'EACCES',
     syscall: 'open',
     path: '/opt/kibana/optimize/bundles/sense.entry.js' },
  isOperational: true,
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/kibana/optimize/bundles/sense.entry.js' }

**Comment by rashidkpc** [comment]
I have no idea why this would cause any issues, especially with sense, maybe a docker cache issue? I suggest opening an issue on the kibana docker container repo.
